In [1]:
import numpy as np
arr1=np.array([2,4,6,8,1,2,4,3,5]).reshape(3,3)
print("matrix 1 : \n", arr1)
arr2=np.array([1,3,5,7,5,6,1,2,4]).reshape(3,3)
print("matrix 2 : \n",arr2)
arr3=np.dot(arr1,arr2)
print("After Matrix Multiplication :\n",arr3)

matrix 1 : 
 [[2 4 6]
 [8 1 2]
 [4 3 5]]
matrix 2 : 
 [[1 3 5]
 [7 5 6]
 [1 2 4]]
After Matrix Multiplication :
 [[36 38 58]
 [17 33 54]
 [30 37 58]]
