In [1]:
import numpy as np
from scipy.linalg import svd
m1=np.array([[2,4],[1,2]])
print(m1)
U,s,VT=svd(m1)
print("U=m*m \n ",U)
print("s=m*n \n ",s)
print("VT=n*n \n ",VT)
print(U @ np.diag(s) @ VT)

[[2 4]
 [1 2]]
U=m*m 
  [[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
s=m*n 
  [5. 0.]
VT=n*n 
  [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
[[2. 4.]
 [1. 2.]]
